import { pdfjs } from 'react-pdf';
import { PageLayout } from 'apps/kanji.sh/src/components/layout/PageLayout';

import './tailwind.css';

export const metadata = {
    title: 'Kanji.sh',
    description: 'Generated by Next.js'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    pdfjs.GlobalWorkerOptions.workerSrc = `//cdnjs.cloudflare.com/ajax/libs/pdf.js/${pdfjs.version}/pdf.worker.min.js`;
    return (
        <html lang="en">
            <head>
                <title>{metadata.title}</title>
                <link rel="icon" href="/favicon.ico" />
                <link rel="apple-touch-icon" href="/logo192.png" />
                <link rel="manifest" href="/manifest.json" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <meta name="charset" content="utf-8" />
                <meta name="theme-color" content="#000" />
                <meta
                    name="viewport"
                    content="minimum-scale=1,initial-scale=1,width=device-width"
                />
                <meta name="title" content={metadata.title} />
                <meta name="description" content={metadata.description} />
            </head>
            <body>
                <PageLayout>{children}</PageLayout>
            </body>
        </html>
    );
}
