# Generates and Uploads PDFs to Supabase Storage bucket.

name: Upload PDFs
on:
  push:
    paths:
      - 'generator/**'
      - '.github/workflows/**'
  workflow_dispatch:


jobs:
  generate-pdfs:
    runs-on: macos-latest
    environment: Production
    if: ${{ !startsWith(github.actor, 'dependabot') }}
    strategy:
      matrix:
        source: [ jlpt, grade, wanikani, frequency, kanjigarden ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install NPM dependencies
        run: npm install

      - name: Generate PDF files
        run: npm run build-worksheets -- --collection=${{ matrix.source }}
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
